options:
  namespace-node-affinity-image:
    type: string
    default: 'charmedkubeflow/namespace-node-affinity:2.2.0'
    description: |
      Container image to be used by the namespace-node-affinity workload.
  settings_yaml:
    type: string
    default: ''
    description: |
      Defines the settings provided to the webhook as a YAML string, as described [here](https://github.com/idgenchev/namespace-node-affinity#configuration) with example [here](https://github.com/idgenchev/namespace-node-affinity/blob/main/examples/sample_configmap.yaml).
